version: 2.1

################# ORB #################
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

################# WORKFLOWS #################
workflows:
  build_and_test:
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - install-dependencies
      - build-and-code-check:
          requires:
            -install-dependencies
      - run-tests:
          requires:
            - build-and-code-check
      - check-repo:
          requires:
            - run-tests

################# JOBS #################
jobs:
  # Install libsodium and any other required dependencies not available on pip
  install-dependencies:
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
      name: libsodium Download.
      command: >-
        wget --quiet
        https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VERSION.tar.gz
      - run:
        name: libsodium Uncompress tar file.
        command: tar xvzf libsodium-$LIBSODIUM_VERSION.tar.gz
      - run:
        name: libsodium Run Configure.
        command: cd libsodium-$LIBSODIUM_VERSION/ && ./configure
      - run:
        name: libsodium Run Make Check.
        command: cd libsodium-$LIBSODIUM_VERSION/ && make && make check
      - run:
        name: libsodium Run Make Install.
        command: cd libsodium-$LIBSODIUM_VERSION/ && sudo make install
      - persist_to_workspace:
          root: .
          paths:
            - .
  # Build the repo and check the code using pyflakes 
  build-and-code-check:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: pip install
          command: cd ~/project; pip install .[all]; cd -
      - run:
          name: code check
          command: cd ~/project; python -m pyflakes .; cd -
      - persist_to_workspace:
          root: .
          paths:
            - .
  # Run unittests 
  run-tests:
    docker:
      - image: cimg/python:3.9
    parallelism: 11
    steps:
      - attach_workspace:
          at: .
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run tests
          command: |
            cd test/unittests
            TESTCLASSES=$(circleci tests glob "test*.py" | sed -e 's/.py//' | circleci tests split)
            python -m unittest $TESTCLASSES -v
      - persist_to_workspace:
          root: .
          paths:
              - .
  # Make sure that the repository is clean after all tests have been run
  check-repo:
    docker:
      - image: cimg/python:3.9
    steps:
      - attach_workspace:
          at: .
      - run:
          name: check repo
          command: cd ~/project; sh test/test_repo_status.sh
